import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Head from 'next/head'
import Header from '@/Components/Ui/Header'
import { Grid } from '@mui/material'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <style>
        @import url('https://fonts.googleapis.com/css2?family=Nunito+Sans:opsz,wght@6..12,200&family=Nunito&display=swap');
      </style>


      <body className={inter.className}>

        {/* <Header /> */}
        <Grid container sx={{ overflow: 'hiden' }}>

          <Header />

          {children}
        </Grid>

      </body>

    </html>
  )
}




{/* <Grid container sx={{ justifyContent: 'center' }}>



  <Grid container md={10.5} lg={11} sx={{ bgcolor: '', zIndex: 100 }}>

    <Header />

    <MobileHeader />

    <Grid container bgcolor='=' sx={{
      mt: { xs: 12, sm: 15, md: 7, lg: 5 },
      flexDirection: { xs: 'column-reverse', sm: 'column-reverse', md: 'row', lg: 'row' },
      height: 'fit-content'
    }}>


      <Grid md={5} lg={5} container sx={{
        bgcolor: '',

      }}>

        <Grid sx={{
          ml: { xs: 2, sm: 10, md: 0, lg: 0 },
          mt: { xs: 6, sm: 5 },
          justifyContent: { xs: 'end' }
        }}>

          <H1 >BUY YOUR</H1>
          <H1 fontWeight='bold'>DREM HOME</H1>
          <H1>IN KYIV!</H1>

          <Box sx={{ bgcolor: '', mt: 3 }}>

            <CustomButton
              background='linear-gradient(90deg, #12C2E9 -15.84%, #C471ED 53.22%, #F64F59 122.28%)'
              color='#FFF'
              border='0px'
            >GET STARTED</CustomButton>

          </Box>

        </Grid>

      </Grid>



      <Grid md={7} lg={7} container bgcolor=''
        sx={{
          justifyContent: { xs: 'center', sm: 'center', md: 'end' },
          alignItems: { xs: 'center' }
        }}
      >

        <Grid
          xs={9} sm={9} md={9} lg={10}
          component='img'
          src='Assets/Banner/Banner.png'
          sx={{
            bgcolor: '',

          }}
        />


      </Grid>

    </Grid>




    <Grid container sx={{ bgcolor: '', justifyContent: 'center', alignItems: 'center', mt: 6.3 }}>

      <H2>
        Senlling a property can be quite challenging
        If you don't have the right tools at your disposals.
      </H2>

    </Grid>


    <Grid container sx={{ bgcolor: '', justifyContent: 'center', alignItems: 'center', mt: 3 }}>

      <H4>
        We help our clients sell, buy or rent properties hassle free. Due to our unparalleled results, expertise and dedication, we rank amongst the top 6 agencies in Kyiv.We are very proud of the service we provide and what our guests have to say about us.
      </H4>

    </Grid>

    <Section1 />





















  </Grid >































  <Grid
    sx={{
      width: '510px',
      height: '400px', flexShrink: 0,
      borderRadius: '510px',
      opacity: 0.56,
      background: '#12C2E9',
      filter: 'blur(200px)',
      zIndex: -2,
      position: 'absolute',
      left: 0,
      top: 500
    }}
  />



  <Grid
    sx={{
      width: '510px',
      height: '350px', flexShrink: 0,
      borderRadius: '510px',
      opacity: 0.56,
      background: '#C471ED',
      filter: 'blur(200px)',
      zIndex: -2,
      position: 'absolute',
      top: 0
    }}
  />

  <Grid
    sx={{
      width: '510px',
      height: '400px',
      flexShrink: 0,
      borderRadius: '50px',
      opacity: 0.56,
      background: '#F64F59',
      filter: 'blur(100px)',
      zIndex: -2,
      position: 'absolute',
      right: 0,
      top: { md: 100, lg: 250 }
    }}
  />


</Grid > */}